# Generated by Django 5.1.4 on 2024-12-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近活跃时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
    ]
