# Generated by Django 5.1.4 on 2024-12-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0002_user_last_active_at_user_last_login_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_at',
        ),
    ]
