# Generated by Django 5.1.4 on 2024-12-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('oAuth', '0003_remove_user_last_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.ManyToManyField(blank=True, related_name='note_users', to='note.note', verbose_name='授权笔记'),
        ),
        migrations.AddField(
            model_name='user',
            name='note_group',
            field=models.ManyToManyField(blank=True, related_name='note_group_users', to='note.notegroup', verbose_name='授权笔记分组'),
        ),
    ]
