# Generated by Django 5.1.4 on 2024-12-31 05:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_id_alter_notegroup_id'),
        ('oAuth', '0004_user_note_user_note_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后活跃时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.ManyToManyField(blank=True, related_name='authorized_users', to='note.note', verbose_name='授权笔记'),
        ),
        migrations.AlterField(
            model_name='user',
            name='note_group',
            field=models.ManyToManyField(blank=True, related_name='authorized_users', to='note.notegroup', verbose_name='授权分组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=20, verbose_name='角色'),
        ),
    ]
