# Generated by Django 5.1.4 on 2024-12-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_id_alter_notegroup_id'),
        ('oAuth', '0005_alter_user_id_alter_user_last_active_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.ManyToManyField(blank=True, related_name='note_users', to='note.note', verbose_name='授权笔记'),
        ),
        migrations.AlterField(
            model_name='user',
            name='note_group',
            field=models.ManyToManyField(blank=True, related_name='note_group_users', to='note.notegroup', verbose_name='授权分组'),
        ),
    ]
