# Generated by Django 5.1.4 on 2025-01-02 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0006_alter_user_note_alter_user_note_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingTalkConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_key', models.CharField(max_length=100, verbose_name='应用Key')),
                ('app_secret', models.CharField(max_length=200, verbose_name='应用密钥')),
                ('agent_id', models.CharField(max_length=100, verbose_name='应用ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '钉钉配置',
                'verbose_name_plural': '钉钉配置',
                'db_table': 'oauth_dingtalk',
            },
        ),
        migrations.CreateModel(
            name='FeiShuConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.CharField(max_length=100, verbose_name='应用ID')),
                ('app_secret', models.CharField(max_length=200, verbose_name='应用密钥')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '飞书配置',
                'verbose_name_plural': '飞书配置',
                'db_table': 'oauth_feishu',
            },
        ),
        migrations.CreateModel(
            name='WeChatWorkConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corp_id', models.CharField(max_length=100, verbose_name='企业ID')),
                ('agent_id', models.CharField(max_length=100, verbose_name='应用ID')),
                ('secret', models.CharField(max_length=200, verbose_name='应用密钥')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '企业微信配置',
                'verbose_name_plural': '企业微信配置',
                'db_table': 'oauth_wechat_work',
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyUserInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('wechat_work', '企业微信'), ('feishu', '飞书'), ('dingtalk', '钉钉')], max_length=20, verbose_name='平台')),
                ('open_id', models.CharField(max_length=100, verbose_name='第三方用户ID')),
                ('union_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='统一ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '第三方用户信息',
                'verbose_name_plural': '第三方用户信息',
                'db_table': 'oauth_third_party_user',
                'unique_together': {('platform', 'open_id')},
            },
        ),
    ]
