# Generated by Django 5.1.4 on 2025-01-02 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0007_dingtalkconfig_feishuconfig_wechatworkconfig_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeChatWorkConfig',
            new_name='WeComConfig',
        ),
        migrations.AlterModelTable(
            name='wecomconfig',
            table='oauth_wecom',
        ),
        migrations.CreateModel(
            name='DingTalkUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=100, verbose_name='钉钉用户ID')),
                ('union_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='统一ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('avatar', models.URLField(blank=True, max_length=500, null=True, verbose_name='头像')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门')),
                ('job_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='工号')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '离职'), ('pending', '待确认')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dingtalk_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '钉钉用户',
                'verbose_name_plural': '钉钉用户',
                'db_table': 'oauth_dingtalk_user',
                'unique_together': {('open_id',)},
            },
        ),
        migrations.CreateModel(
            name='FeiShuUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=100, verbose_name='飞书用户ID')),
                ('union_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='统一ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('avatar', models.URLField(blank=True, max_length=500, null=True, verbose_name='头像')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门')),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='工号')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '离职'), ('pending', '待确认')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feishu_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '飞书用户',
                'verbose_name_plural': '飞书用户',
                'db_table': 'oauth_feishu_user',
                'unique_together': {('open_id',)},
            },
        ),
        migrations.CreateModel(
            name='WeComUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=100, verbose_name='企业微信用户ID')),
                ('union_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='统一ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('avatar', models.URLField(blank=True, max_length=500, null=True, verbose_name='头像')),
                ('qr_code', models.URLField(blank=True, max_length=500, null=True, verbose_name='二维码')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '离职'), ('pending', '待确认')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '企业微信用户',
                'verbose_name_plural': '企业微信用户',
                'db_table': 'oauth_wecom_user',
                'unique_together': {('open_id',)},
            },
        ),
        migrations.DeleteModel(
            name='ThirdPartyUserInfo',
        ),
    ]
