# Generated by Django 5.1.4 on 2025-01-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0008_rename_wechatworkconfig_wecomconfig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wecomuser',
            old_name='open_id',
            new_name='wecom_user_id',
        ),
        migrations.AlterUniqueTogether(
            name='wecomuser',
            unique_together={('wecom_user_id',)},
        ),
        migrations.RemoveField(
            model_name='wecomuser',
            name='union_id',
        ),
    ]
