# Generated by Django 5.1.4 on 2025-01-03 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0009_rename_open_id_wecomuser_wecom_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelTable(
            name='dingtalkconfig',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dingtalkuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='feishuconfig',
            table=None,
        ),
        migrations.AlterModelTable(
            name='feishuuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wecomconfig',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wecomuser',
            table=None,
        ),
    ]
