# Generated by Django 5.1.4 on 2025-01-03 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0014_alter_feishuuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingtalkuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dingtalk_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wecomuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wecom_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
