# Generated by Django 5.1.4 on 2025-01-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0015_alter_dingtalkuser_user_alter_wecomuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dingtalkconfig',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='dingtalkconfig',
            name='app_key',
        ),
        migrations.RemoveField(
            model_name='dingtalkconfig',
            name='app_secret',
        ),
        migrations.AddField(
            model_name='dingtalkconfig',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='APP ID'),
        ),
        migrations.AddField(
            model_name='dingtalkconfig',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='dingtalkconfig',
            name='client_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Client Secret'),
        ),
    ]
