# Generated by Django 5.1.4 on 2025-01-03 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0017_dingtalkconfig_redirect_uri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=100, verbose_name='Client Secret')),
                ('redirect_uri', models.URLField(blank=True, max_length=500, null=True, verbose_name='回调域名')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'GitHub配置',
                'verbose_name_plural': 'GitHub配置',
            },
        ),
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.CharField(max_length=100, unique=True, verbose_name='GitHub ID')),
                ('login', models.CharField(max_length=100, verbose_name='GitHub用户名')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='GitHub昵称')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='GitHub邮箱')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('access_token', models.CharField(max_length=100, verbose_name='访问令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': 'GitHub用户',
                'verbose_name_plural': 'GitHub用户',
            },
        ),
    ]
