# Generated by Django 5.1.4 on 2025-01-03 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0018_githubconfig_githubuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='access_token',
        ),
        migrations.AddField(
            model_name='githubuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
