# Generated by Django 5.1.7 on 2025-03-21 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0019_remove_githubuser_access_token_githubuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=100, verbose_name='Client Secret')),
                ('redirect_uri', models.URLField(blank=True, max_length=500, null=True, verbose_name='回调域名')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Google配置',
                'verbose_name_plural': 'Google配置',
            },
        ),
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_id', models.CharField(max_length=100, unique=True, verbose_name='Google ID')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('given_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名')),
                ('family_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓')),
                ('picture', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('locale', models.CharField(blank=True, max_length=10, null=True, verbose_name='语言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': 'Google用户',
                'verbose_name_plural': 'Google用户',
            },
        ),
        migrations.CreateModel(
            name='OAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('provider',)},
            },
        ),
    ]
