# Generated by Django 5.1.7 on 2025-03-21 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0020_googleconfig_googleuser_oauthconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=100, verbose_name='Client Secret')),
                ('redirect_uri', models.URLField(blank=True, max_length=500, null=True, verbose_name='回调域名')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'GitLab配置',
                'verbose_name_plural': 'GitLab配置',
            },
        ),
        migrations.CreateModel(
            name='GitLabUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gitlab_id', models.CharField(max_length=100, unique=True, verbose_name='GitLab ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('web_url', models.URLField(blank=True, null=True, verbose_name='个人主页')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': 'GitLab用户',
                'verbose_name_plural': 'GitLab用户',
            },
        ),
    ]
