# Generated by Django 5.1.7 on 2025-03-21 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0022_alter_gitlabconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiteeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('redirect_uri', models.CharField(blank=True, max_length=255, verbose_name='重定向URI')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Gitee 配置',
                'verbose_name_plural': 'Gitee 配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiteeUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gitee_id', models.CharField(max_length=50, unique=True, verbose_name='Gitee ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gitee_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gitee 用户',
                'verbose_name_plural': 'Gitee 用户',
                'ordering': ['-created_at'],
            },
        ),
    ]
